### ISSUE TITLE
Testing collision between circle and polygon not working for some coordinates

### ISSUE THREAD

**Issue by andyblem** [robertcorponoi/collider2d#12]
Hie. I have been trying to use your package to test for collisions between a circle and a polygon. The logic returns true for this piece of code:

```
const ballCircle: Circle = new Circle(new Vector(0, 0), 0.115);
const goalLinePolygon: Polygon = new Polygon(new Vector(0, 0),
            [
                new Vector(1.56, -0.04),
                new Vector(1.56, 0.04),
                new Vector(-1.56, 0.04),
                new Vector(-1.56, -0.04),
            ]);

        const collider2d: Collider2d = new Collider2d();
        const hasBallCollidedWithGoalLine: boolean = collider2d.testCirclePolygon(ballCircle, goalLinePolygon) as boolean;

        return hasBallCollidedWithGoalLine;
```
but fails for these values

```
const ballCircle: Circle = new Circle(new Vector(0, -55), 0.115);
const goalLinePolygon: Polygon = new Polygon(new Vector(0, -55),
            [
                new Vector(1.56, -54.96),
                new Vector(1.56, -55.04),
                new Vector(-1.56, -55.04),
                new Vector(-1.56, -54.96),
            ]);

        const collider2d: Collider2d = new Collider2d();
        const hasBallCollidedWithGoalLine: boolean = collider2d.testCirclePolygon(ballCircle, goalLinePolygon) as boolean;

        return hasBallCollidedWithGoalLine;
```
I can't really get whats going on because this is simply a translation of the same objects to some different position. Can you please help me with this.

**Comment by andyblem** [comment]
I figured out the problem. I was making a mistake in inputting the points for the polygon. My point weren't relative to the polygon origin so I had to change my points to :

```
  new Vector(1.56, -0.08),
  new Vector(1.56, 0.08),
  new Vector(-1.56, 0.08),
  new Vector(-1.56, -0.08)
```

**Comment by robertcorponoi** [comment]
Hi, sorry for the late reply, it was a hectic week last week.

I'm glad you were able to figure out the problem. In the docs it mentions the points should be relative to the origin but only in the origin parameter, I should also add this to the points parameter so that it is more clear. Thank you for bringing this to my attention and again I apologize for the delay.
